# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-26 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Planned road work'), (1, 'Special events (fair, sport event, etc.)'), (2, 'Accidents and other unexpected events'), (3, 'Weather condition affecting the road'), (4, 'Status of the road that might affect travellers (potholes, bad pavement, etc.)')], default=0)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting for validation'), (1, 'Valid'), (2, 'Solved')], default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urban_alerts', related_query_name='urban_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
